[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "EmoiEXxiFGwW86FjfXKZVJ2QCsxWJGkeXuYjvmuS8tpu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/johnrambo/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"